### ISSUE TITLE
Declared refresh rate is far from arcade

### ISSUE THREAD

**Issue by rhester72** [MiSTer-devel/Arcade-MoonPatrol_MiSTer#11]
MiSTer core refresh rate: 50.1Hz

Actual arcade refresh rate: 56.737589Hz

**Comment by M-Walrus** [comment]
This is an interesting find. I wonder if this discrepancy in refresh rate could be what is causing the sound to glitch after playing for a while?

**Comment by M-Walrus** [comment]
This must be why I get a rolling image on CRT for this core. My CRT is NTSC-only, so the 50hz signal its trying to put out is completely incompatible.

**Comment by wwark** [comment]
This issue maybe fixed with the last release.
We have two choices Original or Pal refresh rate.

**Comment by rhester72** [comment]
Confirmed!  The original refresh rate is now an option (though rather hard for many displays to sync to properly, as expected!).  Closing.
